### ISSUE TITLE
Tradeshop-ARM Update?

### ISSUE THREAD

**Issue by blockswerker** [Tradeshop/tradeshop-ARM#2]
I've installed Tradeshop (2.3.2-DEV-2021-11-08T22.31.33), then later added Advanced Region Market. I notice the Tradeshop-ARM hasn't been updated in a while, do I need to downgrade to the ARM version or have the features of Tradeshop-ARM been rolled into the main plugin?

**Comment by KillerOfPie** [comment]
> I've installed Tradeshop (2.3.2-DEV-2021-11-08T22.31.33), then later added Advanced Region Market. I notice the Tradeshop-ARM hasn't been updated in a while, do I need to downgrade to the ARM version or have the features of Tradeshop-ARM been rolled into the main plugin?

Add-ons don't need updates unless something break/stops working.
